title: Blue Coral Services - An Apple Consultants Network member
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3042553
  brandStrength: 0.9217336548026651
  lightness: 0.8585709
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  rhythmicContrast: 0.4489362
cta:
  bucket: null
  version: null
  domain: null
name: bluecoralservices
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7396529035177082
layout_spectrum: 1
