title: Blue Coral Services - An Apple Consultants Network member
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7510638
  brandStrength: 1
  lightness: 0.8585709
  brandColors:
    - '#6789C6'
    - '#AFA9AD'
    - '#CDDCEF'
    - '#1D3454'
    - '#6C6465'
  rhythmicContrast: 0.7510638
cta:
  bucket: null
  version: null
  domain: null
name: bluecoralservices
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6829787
layout_spectrum: 1
